<a href="https://colab.research.google.com/github/Saifullah785/deep-learning-ai-journey/blob/main/Lecture_09_backpropagation_basic_code/Lecture_09_Part_2_backpropagation_using_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries: numpy for numerical operations and pandas for data manipulation

import numpy as np
import pandas as pd


In [2]:
# Create a pandas DataFrame with sample data.

df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])


In [3]:
# Display the created DataFrame.

df


cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
# Import TensorFlow and Keras, along with necessary layers for building the neural network.

import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
# Create a sequential Keras model.

model = keras.Sequential()

# Add a dense layer with 2 units and linear activation. Specify the input dimension as 2.
model.add(Dense(2,activation='linear',input_dim=2))

# Add another dense layer with 1 unit and linear activation.
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
# Display a summary of the model architecture.

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
# Get and display the initial weights of the model.

model.get_weights()

[array([[ 1.0569564,  1.055854 ],
        [ 1.1844712, -1.0508711]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0902408 ],
        [-0.14751327]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
# Define new weights to set for the model.

new_weights = [np.array([[0.1 ,0.1],[0.1 , 0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]


In [9]:
# Set the model's weights to the new weights.

model.set_weights(new_weights)

In [10]:
# Get and display the updated weights of the model.

model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
# Define the optimizer for the model (Adam with a specified learning rate).

optimizer = keras.optimizers.Adam(learning_rate=0.001)

# Compile the model, specifying the loss function (mean squared error) and optimizer.

model.compile(loss="mean_squared_error",optimizer=optimizer)

In [12]:
# Train the model using the data from the DataFrame.
# The input features are all columns except the last one, and the target is the 'lpa' column.
# Train for 75 epochs with a batch size of 1 and verbose output.

model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 31.8140
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 29.2484
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24.8341 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 27.2035 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32.7552 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 25.7877 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31.9356
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 25.0446
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 28.1282
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 20.0568
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 23.8939
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 29.1709
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 28.2275
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 17.5901
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 22.1172
Epoch 16/75
4/4

In [13]:
# Get and display the final weights of the model after training.

model.get_weights()

[array([[0.37371066, 0.37371066],
        [0.3656067 , 0.3656067 ]], dtype=float32),
 array([0.27234894, 0.27234894], dtype=float32),
 array([[0.37295806],
        [0.37295806]], dtype=float32),
 array([0.20465353], dtype=float32)]